@api=http://localhost:4000/api

### 
# @name get
GET {{api}}/project-settings/1234
Content-Type: application/json

### 
# @name insertBulk
POST {{api}}/project-settings/insertBulk
Content-Type: application/json

{
  "idOffset": 0,
  "count": 1000000,
  "batchSize": 1000
}

### 
# @name update
PUT {{api}}/project-settings/1234
Content-Type: application/json

{
  "settings": [
    {
      "key": "darkMode",
      "value": "false",
    }
  ]
}