@api=http://localhost:4000/api

### prjs
# @name prjs
GET {{api}}/project-settings/1234
Content-Type: application/json

### project management data
# @name InsertPmDataBulk
POST {{api}}/project-settings/insertBulk
Content-Type: application/json

{
  "idOffset": 0,
  "count": 1000000,
  "batchSize": 1000
}